# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ""

setup(
    long_description=readme,
    name="sim-lang",
    version="0.2.0",
    description="benjamin asset simulation langugage",
    python_requires="==3.*,>=3.8.0",
    author="Kyoodong",
    author_email='wind.dong.dream@gmail.com"',
    packages=["language", "language.execute", "test"],
    package_dir={"": "sim_lang"},
    package_data={},
    install_requires=[
        "anytree==2.*,>=2.8.0",
        "boto3==1.*,>=1.17.27",
        "docstring-parser==0.*,>=0.7.3",
        "pandas==1.*,>=1.2.1",
        "pymysql==1.*,>=1.0.2",
        "pytest==6.*,>=6.2.2",
        "python-dotenv==0.*,>=0.15.0",
        "utils",
    ],
    dependency_links=["git+https://github.com/benjamin-asset/utils.git#egg=utils"],
    extras_require={"dev": ["dephell==0.*,>=0.8.3"]},
)
